ccflags-y += -Idrivers/cam_utils
ccflags-y += -Idrivers/cam_cpas/include
ccflags-y += -Idrivers/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/cam_sensor_module/cam_sensor_utils
ccflags-y += -Idrivers/cam_req_mgr
ccflags-y += -Idrivers/cam_sensor_module/cam_cci
ccflags-y += -Idrivers/cam_smmu/
obj-$(CONFIG_SPECTRA_CAMERA) += 3dsl_eeprom_dev.o 3dsl_eeprom_core.o 3dsl_eeprom_soc.o
